# -*- coding: utf-8 -*-
"""Python_Project_Beginner

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hxQwYoLKcUoYV1UYFr0QZmouLDTz0CvR

**INVENTORY MANAGEMENT SYSTEM**

Project Strcuture

-- Model.py

-- Bussiness_logic.py

-- Json.py    storage

-- Main.py or User Interface
"""

# Creating the Model.py in Inventory managemnt system
# step - 1 class for the inventory management system
class product():
  def __init__(self,p_id,p_name,p_price,P_quantity):
    self.p_id = p_id
    self.p_name = p_name
    self.p_price = p_price
    self.p_quantity = p_quantity

    # Product actons like selling , restocking
    def sell_p(self,amount):
      if 0 < amount <= self.P_quantity:
        self.p_quantity =- amount
      else:
        print('out of stock')

    def restock_p(self,amount):
      if amount > 1 :
        self.p_quantity =+ amount
      else:
        print('no stock added')

    # Serialization (changing objects to Json)
    def to_dict(self):
      return {'p_id': p_id,'p_name': p_name,'p_price':p_price,'P_quantity':P_quantity}

# step - 2 Creating Business Logic
import json
# from model.py import product

class inventory_management():
  def __init__(self):
    self.products = []

 # add prodcuts
  def add_product(self,p_id,p_name,p_price,p_quantity):
    for p in self.products:
      self.products.append(p)

 # view products
  def view_product(self,p_id):
    for p in self.products:
      if p_id == p.p_id:
        return p
      else :
        print('no item found')

  # update price
  def price_update(self,product,price):
    if price > p_price or price < p_price :
      price_update = p_price
      return price_update
    else :
      print('no change')


 # save & load model
  def save_model(self):
    with open('business.json','w') as file:
      data = json.dump([p.to_dict() for p in self.products],file)

  def load_model(self):
    with open('business.json', 'r') as file :
      data = json.load(file)
      self.products = [product(p['p_id'],p['p_name'],p['p_price'],p['p_quantity']) for p in data]
      return True

# user interface step - 3
import json

def main():
  business = inventory_management()
  business.load_model()

  while True:
    print('\nInventory Management System')
    print('1. Add product')
    print('2. View product')
    print('3. Update product price')
    print('4. Save data')
    print('5. Load data')
    print('6. Exit')

    choice_str = input('Enter your choice: ')

    if choice == 1:
      p_id = input('Enter product ID: ')
      p_name = input('Enter product name: ')
      p_price = input('Enter product price: ')
      p_quantity = input('Enter product quantity: ')
      business.add_product(p_id,p_name,p_price,p_quantity)


    elif choice == "4":
        inventory.save_to_file()
        break

